[package]
name = "rs-net-snmp"
version = "0.1.0"
authors = ["William Brown <william@blackhats.net.au>"]
build = "build.rs"

[build-dependencies]
gcc = "0.3"

[dependencies]
libc = "0.2.0"

[lib]
path="src/rs_net_snmp/lib.rs"

[[bin]]
path="src/rs_net_snmp_utils/main.rs"
name="snmptest"
