[package]
name = "rs-net-snmp"
version = "0.1.0"
authors = ["William Brown <wibrown@redhat.com>"]
build = "build.rs"

[build-dependencies]
gcc = { path = "../gcc-rs" }

[dependencies]
libc = "0.2.0"

[lib]
path="src/rs_net_snmp/lib.rs"

[[bin]]
path="src/rs_net_snmp_utils/main.rs"
name="snmptest"
